### ISSUE TITLE
addon.setup.php needs updating for EE6 namespace change

### ISSUE THREAD

**Issue by jcogs-design** [EllisLab/Reading-Time#1]
Currently using this (very simple) add-on in EE6 causes a warning due to the addon.setup.php file referencing the wrong namespace.

Updating the file to have the following entry for namespace allows the add-on to work - but presumably some other values are also needed for author and author_url before an update can be published.

```
<?php

return array(
	'author'      => 'EllisLab',
	'author_url'  => 'https://ellislab.com/',
	'name'        => 'Reading Time',
	'description' => 'Outputs the estimated reading time for the given content.',
	'version'     => '2.0.1',
	'namespace'   => 'ExpressionEngine\Addons\ReadingTime',
	'settings_exist' => FALSE,
	'plugin.typography' => FALSE
);
```

**Comment by intoeetive** [comment]
@jcogs-design the repo file already has this changed: https://github.com/EllisLab/Reading-Time/blob/master/reading_time/addon.setup.php

**Comment by jcogs-design** [comment]
ahah - well that's a bit weird.  When I posted the issue on the EllisLab github I could find no indication there that there was a newer build... but good news if there is.  Kudos to you for doing!
